### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by engram-design** [kymar/craft_cloner#3]
Any plans for a Craft 3 version of this? Happy to submit a PR if you'd like to continue development on this.

**Comment by HellPat** [comment]
Seems to be dead?
@kymar would you like to maintain this plugin and upgrade to craft3?

If not I'd maybe fork it if you're okay with it?

**Comment by kymar** [comment]
Sorry I replied to this on twitter, basically I have been busy as I've recently got married, I'm meaning to get back into looking in to so me craft stuff but don't have as much time as I used to, I used to actively work with craft on a day to day basis and I don't anymore, If you are happy to wait I will be looking at a craft 3 version, if you are desperate, then feel free to fork and make a craft 3 version but just obviously tag me in it somewhere 👍

**Comment by engram-design** [comment]
@kymar FYI, we've already started this as a separate plugin, just in case you didn't have plans (or time) to keep developing things!

**Comment by kymar** [comment]
@engram-design Oh ok then, do you have a like to the repo or is it still being developed ?

**Comment by engram-design** [comment]
@kymar No repo just yet, but will be sharing it soon

**Comment by userAW** [comment]
Are there any updates on this? We just upgraded to Craft3 and used Cloner in our Craft2 workflow. Would love to see a replacement!

**Comment by engram-design** [comment]
@userAW Just finished our take on the plugin via https://github.com/verbb/cloner

Adds support for cloning:
- Asset Transforms
- Category Groups
- Entry Types
- Global Sets
- Sections
- Service
- Tag Groups
- User Groups
- Volume

**Comment by userAW** [comment]
Great, thank you!

Aidel
